declare const React: any
declare const ReactDOM: any
declare const useState: any
declare const useEffect: any
declare const useCallback: any
declare const useMemo: any
declare const useReducer: any
declare const useRef: any
declare const useContext: any